"""Rebuild the embedded RGB565 pixel art. Requires Pillow; no runtime file I/O."""
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
images = []

def add(name, file, rect=None, key=None, size=None):
    im = Image.open(ROOT / 'assets' / file).convert('RGBA')
    if rect:
        im = im.crop(rect)
    if key is not None:
        im.putdata([(*p[:3], 0 if p[:3] == key or
                    (key == (111,109,81) and p[:3] == (249,48,61)) else p[3])
                    for p in im.getdata()])
    if size:
        im = im.resize(size, Image.Resampling.NEAREST)
    images.append((name, im))

olive = (111, 109, 81)
add('knight_idle', 'knight.png', (4,4,58,58), olive)
for i in range(8):
    x = [5,62,119,176,233,290,347,404][i]
    add(f'knight_walk{i}', 'knight.png', (x,121,x+53,175), olive)
add('knight_jump', 'knight.png', (66,62,119,116), olive)
for i in range(3):
    add(f'knight_attack{i}', 'knight.png', (5+92*i,244,94+92*i,306), olive)
for i in range(4):
    add(f'bat{i}', 'bat.png', (1+34*i,1,33+34*i,33), olive)
for i in range(7):
    add(f'ghoul{i}', 'ghoul.png', (57*i,0,57*(i+1),60), size=(43,45))
for i in range(5):
    add(f'wizard{i}', 'wizard.png', (81*i,0,81*(i+1),66))
add('window', 'architecture.png', (0,0,160,192), (39,38,56))
add('column', 'architecture.png', (176,0,304,192), (39,38,56))
add('foreground', 'architecture.png', (229,94,250,192), (39,38,56), (21,170))
add('altar', 'architecture.png', (320,0,448,192), (39,38,56))
add('crest', 'architecture.png', (464,0,544,192), (39,38,56))
add('landscape', 'landscape.png')
add('floor', 'tiles.png', (64,160,112,208))
add('brick', 'tiles.png', (240,32,272,80))
add('door', 'tiles.png', (288,16,320,80))

out = ['/* Generated by tools/build_assets.py; see assets/CREDITS.md. */']
out += ['typedef struct { int w, h; const uint16_t *pixels; } Art;']
for name, im in images:
    values = []
    for r,g,b,a in im.getdata():
        values.append(0 if a < 128 else max(1, ((r>>3)<<11)|((g>>2)<<5)|(b>>3)))
    out.append(f'static const uint16_t data_{name}[] = {{')
    out.extend(','.join(str(v) for v in values[i:i+32])+',' for i in range(0,len(values),32))
    out.append('};')
    out.append(f'static const Art art_{name} = {{{im.width},{im.height},data_{name}}};')
(ROOT / 'source/art.inc').write_text('\n'.join(out)+'\n')
